# fly.toml app configuration file generated for code-challenger-client-ancient-brook-9001 on 2024-02-10T13:48:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'code-challenger-client-ancient-brook-9001'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[scale]
min = 1
max = 1